package by.asushenya.total.logic;

public enum CommandName {
	AUTHORIZATION_USER_COMMAND,
	GET_ALL_USER_RATES_COMMAND,
	REGISTRATION_USER_COMMAND,
	GET_ALL_USERS_COMMAND,
	GET_ALL_GAMES_COMMAND,
	GET_ALL_TEAMS_COMMAND,
	ADD_NEW_GAME_COMMAND,
	MAKE_RATE_COMMAND,
	GET_PAGE_WITH_GAMES_COMMAND,
	GET_GAMES_BY_KIND_COMMAND,
	GET_PERSONAL_PAGE_COMMAND,
	LOCALIZATION_COMMAND,
	LOG_OUT_COMMAND,
	
	MAKE_RATE_INIT_COMMAND,
	
	NO_SUCH_COMMAND
}
