package by.asushenya.total.controller;

public enum CommandName {
	AUTHORIZATION_USER_COMMAND,
	AUTHORIZATION_USER_SIGN_IN_COMMAND,
	AUTHORIZATION_USER_SIGN_OUT_COMMAND,
	GET_ALL_USER_RATES_COMMAND,
	
	GET_ALL_USERS_COMMAND,
	GET_ALL_GAMES_COMMAND,
	GET_ALL_TEAMS_COMMAND,
	
	MAKE_RATE_COMMAND,
	GET_PAGE_WITH_GAMES_COMMAND,
	//GET_GAMES_BY_KIND_COMMAND,
	GET_PERSONAL_PAGE_COMMAND,
	LOCALIZATION_COMMAND,
	LOG_OUT_COMMAND,	
	MAKE_RATE_INIT_COMMAND,
	

	SET_NEW_GAME_RATES_AJAX_COMMAND,
	MAKE_GAME_INVISIBLE_AJAX_COMMAND,
	ADD_NEW_GAME_AJAX_COMMAND,
	GET_TEAMS_OF_SOME_GAME_KIND_AJAX_COMMAND,
	REGISTRATION_USER_AJAX_COMMAND,
	
	NO_SUCH_COMMAND
}
