package by.asushenya.total.controller;

public enum CommandName {
	INITIALIZATION_SOURCE_COMMAND,
	DESTROY_SOURCE_COMMAND,
	
	AUTHORIZATION_USER_SIGN_OUT_COMMAND,
	GET_ALL_USER_RATES_COMMAND,
	
	MAKE_RATE_COMMAND,
	GET_PAGE_WITH_GAMES_COMMAND,
	GET_PAGE_WITH_USERS_COMMAND,
	GET_PAGE_WITH_RATES_COMMAND,
	GET_PERSONAL_PAGE_COMMAND,
	CHANGE_LOCALIZATION_COMMAND,
	LOG_OUT_COMMAND,	
	MAKE_RATE_INIT_COMMAND,
	INITIALIZE_ADD_NEW_GAME_PAGE_COMMAND,	
	
	NO_SUCH_COMMAND
}
